# Currently, the supported languages are: pl_PL and en_US
langType: en_EN

basteType: SQLite

# MYSQL -> Example: jdbc:mysql://<user>:<password>@<adress>:<port>/<base_name>
# MONGODB -> Example: mongodb+srv://<db_username>:<dbpassword>@<adress>/?retryWrites=true@w=majorty@appName=<cluster>
# SQLite -> Example: jdbc:sqlite:plugins/EChestPlus/enderchest.db
databaseConnectionUri: jdbc:sqlite:plugins/EChestPlus/enderchest.db

# EnderChest Size
enderChestSize: 27

# Item look
upgraderItem:
  - ItemStack:
      material: LEGACY_PAPER
      meta:
        display: '&5&lRozszerzenie enderchesta'
        lore:
          - ''
          - ''
          - ''
          - ''
          - ''
          - ''
          - ''
        enchantments:
          LURE: 1
        flags:
          - HIDE_ENCHANTS
    modelData: 1