name: '${project.name}'
version: '${project.version}'
authors: [Nightzy.net]
website: '${project.url}'
main: net.nightzy.echestplus.EChestPlusPlugin
api-version: '${apiVersion}'

commands:
  ecreload:
    description: Reload the plugin configuration.
    usage: /ecreload
    permission: echestplus.reload
    permission-message: You do not have permission to use this command.